algoritmo "Exercicio 3 - Salario funcionario"
var
salario: real
nome: caractere
inicio
      Escreval("======== SALÁRIO FUNCIONÁRIO ========")
      Escreval("Olá, digite o seu nome, por favor!")
      Leia(nome)
      Escreval("Digite o seu salário")
      Leia(salario)
      Escreval("Nome do funcionário: ", nome)
      Escreval("Salário:", salario)
      Escreval("O funcionário ", nome ," tem um salário de R$:", salario, " em Setembro.")
fimalgoritmo